<a href="https://colab.research.google.com/github/SpellOnYou/10000-days-of-code/blob/master/code/python/testing_different_version_of_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**CUDA version: 10.1**

[timezone](https://www.zeitverschiebung.net/en/timezone/africa--casablanca) of GPU is casablanca/africa

**Python version 3.6.9**

refer [this site](https://pytorch.org/get-started/previous-versions/) when you have trouble with using different version of pytorch

In [0]:
!nvidia-smi

Wed May 20 10:14:37 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.82       Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   40C    P0    26W / 250W |      0MiB / 16280MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU  

In [0]:
!python -c "import sys; print(sys.version)"

3.6.9 (default, Apr 18 2020, 01:56:04) 
[GCC 8.4.0]


## pytorch: 1.5.0+cu101

In [0]:
!python -c "import torch; print(torch.__version__)"

1.5.0+cu101


In [0]:
import torch
a = torch.arange(0, 100)
p = torch.linspace(0.01,1,100)
a, p

(tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
         18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
         36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
         54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
         72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89,
         90, 91, 92, 93, 94, 95, 96, 97, 98, 99]),
 tensor([0.0100, 0.0200, 0.0300, 0.0400, 0.0500, 0.0600, 0.0700, 0.0800, 0.0900,
         0.1000, 0.1100, 0.1200, 0.1300, 0.1400, 0.1500, 0.1600, 0.1700, 0.1800,
         0.1900, 0.2000, 0.2100, 0.2200, 0.2300, 0.2400, 0.2500, 0.2600, 0.2700,
         0.2800, 0.2900, 0.3000, 0.3100, 0.3200, 0.3300, 0.3400, 0.3500, 0.3600,
         0.3700, 0.3800, 0.3900, 0.4000, 0.4100, 0.4200, 0.4300, 0.4400, 0.4500,
         0.4600, 0.4700, 0.4800, 0.4900, 0.5000, 0.5100, 0.5200, 0.5300, 0.5400,
         0.5500, 0.5600, 0.5700, 0.5800, 0.5900, 0.6000, 0

In [0]:
len(a), len(p)

(100, 100)

In [0]:
p[99], p[-1]

(tensor(1.), tensor(1.))

---

## pytorch: 1.4.0+cu101

* [wheel pytorch](https://download.pytorch.org/whl/torch_stable.html)
* [Issues torch==1.4.0 is broken when using CUDA 10.1](https://github.com/pytorch/pytorch/issues/37113)
* `https://download.pytorch.org/whl/cu101/torch-1.4.0-cp36-cp36m-linux_x86_64.whl`

In [0]:
!pip install https://download.pytorch.org/whl/cu101/torch-1.4.0-cp36-cp36m-linux_x86_64.whl

     |████████████████████████████████| 753.4MB 22kB/s 
ERROR: torchvision 0.6.0+cu101 has requirement torch==1.5.0, but you'll have torch 1.4.0 which is incompatible.
  Found existing installation: torch 1.5.0+cu101
    Uninstalling torch-1.5.0+cu101:
      Successfully uninstalled torch-1.5.0+cu101


It warns me I couldn't be able to use torchvision

In [0]:
import torch
torch.__version__

'1.4.0'

In [0]:
a = torch.arange(0, 100)
p = torch.linspace(0.01,1,100)
a, p

(tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
         18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
         36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
         54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
         72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89,
         90, 91, 92, 93, 94, 95, 96, 97, 98, 99]),
 tensor([0.0100, 0.0200, 0.0300, 0.0400, 0.0500, 0.0600, 0.0700, 0.0800, 0.0900,
         0.1000, 0.1100, 0.1200, 0.1300, 0.1400, 0.1500, 0.1600, 0.1700, 0.1800,
         0.1900, 0.2000, 0.2100, 0.2200, 0.2300, 0.2400, 0.2500, 0.2600, 0.2700,
         0.2800, 0.2900, 0.3000, 0.3100, 0.3200, 0.3300, 0.3400, 0.3500, 0.3600,
         0.3700, 0.3800, 0.3900, 0.4000, 0.4100, 0.4200, 0.4300, 0.4400, 0.4500,
         0.4600, 0.4700, 0.4800, 0.4900, 0.5000, 0.5100, 0.5200, 0.5300, 0.5400,
         0.5500, 0.5600, 0.5700, 0.5800, 0.5900, 0.6000, 0

In [0]:
len(a), len(p)

(100, 100)

In [0]:
p[99], p[-1]

(tensor(1.0000), tensor(1.0000))

## Reference

API, which is pytorch compile internally
- Library API > [Function torch::linspace](https://pytorch.org/cppdocs/api/function_namespacetorch_1a28ee7a461a70fd65a6ad3ab3ede48e66.html)

pytorch official document of linspace

- [v1.3.1](https://pytorch.org/docs/1.3.1/torch.html?highlight=linspace#torch.linspace)
- [v1.4.0](https://pytorch.org/docs/1.4.0/torch.html?highlight=linspace#torch.linspace)
- [v1.5.0](https://pytorch.org/docs/stable/torch.html#torch.linspace)